apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: k2tpp0n3y-go 
  janus-idp.io/tekton: k2tpp0n3y-go
  backstage.io/kubernetes-id: k2tpp0n3y-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: k2tpp0n3y-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  